import React, { useState } from 'react';
import { 
  X, 
  FileCode, 
  Download, 
  Copy, 
  Check, 
  CheckCircle2, 
  ShieldCheck, 
  Layers, 
  Cpu, 
  Zap,
  Play
} from 'lucide-react';
import { 
  KimiModelConfig, 
  SiliconProcessConfig, 
  EDAOptimizationMetrics, 
  PowerMetrics 
} from '../types/eda';
import { generateVerilogRTL } from '../utils/edaCalculations';
import { GdsiiStreamView } from './GdsiiStreamView';

interface RTLSignoffModalProps {
  isOpen: boolean;
  onClose: () => void;
  model: KimiModelConfig;
  siliconConfig: SiliconProcessConfig;
  metrics: EDAOptimizationMetrics;
  powerMetrics: PowerMetrics;
}

export const RTLSignoffModal: React.FC<RTLSignoffModalProps> = ({
  isOpen,
  onClose,
  model,
  siliconConfig,
  metrics,
  powerMetrics,
}) => {
  const [copied, setCopied] = useState(false);
  const [activeSubTab, setActiveSubTab] = useState<'verilog' | 'signoff_report' | 'def_manifest' | 'gdsii_stream'>('signoff_report');

  if (!isOpen) return null;

  const verilogCode = generateVerilogRTL(model, siliconConfig);

  const handleCopyVerilog = () => {
    navigator.clipboard.writeText(verilogCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadFile = (filename: string, content: string) => {
    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = filename;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const defManifest = `# ==============================================================================
# DEF Floorplan & Macro Placement Manifest
# Generated by Kimi K3 On-Silicon ASIC EDA Suite
# ==============================================================================
VERSION 5.8 ;
DESIGN asic_kimi_k3_top ;
UNITS DISTANCE MICRONS 1000 ;

DIEAREA ( 0 0 ) ( ${siliconConfig.dieWidthMm * 1000} ${siliconConfig.dieHeightMm * 1000} ) ;

COMPONENTS 8 ;
- macro-weight-01 3D_RERAM_TIER_64_MACRO + PLACED ( 2000 2000 ) N ;
- macro-weight-02 3D_RERAM_TIER_64_MACRO + PLACED ( 13000 2000 ) N ;
- macro-compute-01 SYSTOLIC_MLA_GEMM_CORE + PLACED ( 2000 12000 ) N ;
- macro-compute-02 SYSTOLIC_MOE_CORE + PLACED ( 9000 12000 ) N ;
- macro-mla-kv MLA_KV_CACHE_SRAM_BANK + PLACED ( 16000 12000 ) N ;
- macro-pcie-cxl PCIE_GEN5_CXL3_PHY_16LANE + PLACED ( 2000 19000 ) N ;
- macro-noc-router 2D_MESH_NOC_CROSSBAR + PLACED ( 13000 19000 ) N ;
- macro-rot-safety INDUSTRIAL_SAFETY_ROT + PLACED ( 19000 19000 ) N ;
END COMPONENTS

PINS 34 ;
- pcie_rx_p[15:0] + NET pcie_rx_p + DIRECTION INPUT + USE SIGNAL ;
- pcie_tx_p[15:0] + NET pcie_tx_p + DIRECTION OUTPUT + USE SIGNAL ;
- sys_clk_p + NET sys_clk_p + DIRECTION INPUT + USE CLOCK ;
- rst_n + NET rst_n + DIRECTION INPUT + USE RESET ;
END PINS

END DESIGN
`;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in duration-200 font-mono">
      <div className="relative w-full max-w-4xl bg-[#08090D] border border-white/20 shadow-2xl flex flex-col max-h-[90vh] overflow-hidden text-[#D1D5DB]">
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-[#0A0C12]">
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-blue-600/10 text-blue-400 border border-blue-500/20">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-white uppercase tracking-wider">
                ASIC Signoff Verification & Hardware RTL Exporter
              </h2>
              <p className="text-[10px] text-zinc-400 uppercase tracking-widest mt-0.5">
                Single-Chip Monolithic 3D Silicon • PCIe Gen 5 / CXL 3.0 • Kimi K3 Weight Integration
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 text-zinc-400 hover:text-white border border-transparent hover:border-white/20 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Sub-navigation */}
        <div className="flex items-center justify-between px-6 py-2.5 bg-[#050608] border-b border-white/10 text-xs font-mono">
          <div className="flex space-x-2 overflow-x-auto">
            <button
              onClick={() => setActiveSubTab('signoff_report')}
              className={`px-3 py-1 uppercase tracking-wider text-[11px] font-semibold transition cursor-pointer ${
                activeSubTab === 'signoff_report'
                  ? 'bg-blue-600 text-white border border-blue-500'
                  : 'text-zinc-400 hover:text-white hover:bg-white/5 border border-transparent'
              }`}
            >
              Signoff Checklist & Telemetry
            </button>
            <button
              onClick={() => setActiveSubTab('verilog')}
              className={`px-3 py-1 uppercase tracking-wider text-[11px] font-semibold transition cursor-pointer ${
                activeSubTab === 'verilog'
                  ? 'bg-blue-600 text-white border border-blue-500'
                  : 'text-zinc-400 hover:text-white hover:bg-white/5 border border-transparent'
              }`}
            >
              SystemVerilog RTL (CXL / ASIC Top)
            </button>
            <button
              onClick={() => setActiveSubTab('def_manifest')}
              className={`px-3 py-1 uppercase tracking-wider text-[11px] font-semibold transition cursor-pointer ${
                activeSubTab === 'def_manifest'
                  ? 'bg-blue-600 text-white border border-blue-500'
                  : 'text-zinc-400 hover:text-white hover:bg-white/5 border border-transparent'
              }`}
            >
              Floorplan DEF 5.8
            </button>
            <button
              onClick={() => setActiveSubTab('gdsii_stream')}
              className={`px-3 py-1 uppercase tracking-wider text-[11px] font-semibold transition cursor-pointer flex items-center space-x-1.5 ${
                activeSubTab === 'gdsii_stream'
                  ? 'bg-blue-600 text-white border border-blue-500'
                  : 'text-zinc-400 hover:text-white hover:bg-white/5 border border-transparent'
              }`}
            >
              <Layers className="w-3.5 h-3.5" />
              <span>GDSII Layout Stream (Calibre / OASIS)</span>
            </button>
          </div>

          <div className="flex items-center space-x-2">
            {activeSubTab !== 'gdsii_stream' && (
              <button
                onClick={() => setActiveSubTab('gdsii_stream')}
                className="flex items-center space-x-1.5 px-2.5 py-1 bg-blue-600 hover:bg-blue-500 text-white border border-blue-500 uppercase tracking-wider text-[10px] font-bold transition cursor-pointer whitespace-nowrap"
              >
                <Play className="w-3 h-3" />
                <span>Simulate GDSII Export</span>
              </button>
            )}
            {activeSubTab === 'verilog' && (
              <>
                <button
                  onClick={handleCopyVerilog}
                  className="flex items-center space-x-1 px-2.5 py-1 bg-[#08090D] hover:bg-white/10 text-white border border-white/10 uppercase tracking-wider text-[10px] transition cursor-pointer"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? 'Copied' : 'Copy RTL'}</span>
                </button>
                <button
                  onClick={() => handleDownloadFile('asic_kimi_k3_top.v', verilogCode)}
                  className="flex items-center space-x-1 px-2.5 py-1 bg-emerald-600 hover:bg-emerald-500 text-white border border-emerald-500 uppercase tracking-wider text-[10px] font-bold transition cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download .v</span>
                </button>
              </>
            )}
            {activeSubTab === 'def_manifest' && (
              <button
                onClick={() => handleDownloadFile('kimi_k3_floorplan.def', defManifest)}
                className="flex items-center space-x-1 px-2.5 py-1 bg-emerald-600 hover:bg-emerald-500 text-white border border-emerald-500 uppercase tracking-wider text-[10px] font-bold transition cursor-pointer"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download .def</span>
              </button>
            )}
          </div>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto max-h-[calc(90vh-160px)] space-y-6">
          {activeSubTab === 'signoff_report' && (
            <div className="space-y-6">
              {/* Comprehensive EDA Signoff Table */}
              <div className="p-4 bg-[#050608] border border-white/10 space-y-3 font-mono text-xs">
                <div className="flex justify-between items-center pb-2 border-b border-white/10 text-zinc-400 uppercase tracking-wider text-[10px] font-bold">
                  <span>Signoff Verification Gate</span>
                  <span>Status</span>
                  <span>Measured Value</span>
                  <span>Pass/Fail Margin</span>
                </div>

                <div className="flex justify-between items-center py-2 border-b border-white/10">
                  <div>
                    <div className="font-semibold text-white uppercase tracking-wider">Physical DRC (Design Rule Check)</div>
                    <div className="text-[10px] text-zinc-500 font-mono">Die boundary 24x24mm / 858mm² Reticle limit</div>
                  </div>
                  <span className="px-2 py-0.5 bg-emerald-950/50 text-emerald-400 border border-emerald-500/30 text-[9px] font-bold uppercase tracking-wider">
                    PASSED
                  </span>
                  <span className="text-zinc-300">{metrics.drcViolationCount} Violations</span>
                  <span className="text-emerald-400 font-semibold">+282 mm² Reticle Headroom</span>
                </div>

                <div className="flex justify-between items-center py-2 border-b border-white/10">
                  <div>
                    <div className="font-semibold text-white uppercase tracking-wider">On-Silicon Weight Storage Fit</div>
                    <div className="text-[10px] text-zinc-500 font-mono">Zero External DRAM requirement</div>
                  </div>
                  <span className="px-2 py-0.5 bg-emerald-950/50 text-emerald-400 border border-emerald-500/30 text-[9px] font-bold uppercase tracking-wider">
                    100% FIT
                  </span>
                  <span className="text-zinc-300">{metrics.onChipStorageAvailableGB} GB Silicon / {metrics.totalStorageRequiredGB} GB Weight</span>
                  <span className="text-emerald-400 font-semibold">100% Pretrained Weights On-Chip</span>
                </div>

                <div className="flex justify-between items-center py-2 border-b border-white/10">
                  <div>
                    <div className="font-semibold text-white uppercase tracking-wider">Thermal Junction Signoff (Tj Max)</div>
                    <div className="text-[10px] text-zinc-500 font-mono">Continuous 100k token load at 45°C ambient</div>
                  </div>
                  <span className={`px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider border ${metrics.thermalThrottling ? 'bg-rose-950/50 text-rose-400 border-rose-500/30' : 'bg-emerald-950/50 text-emerald-400 border-emerald-500/30'}`}>
                    {metrics.thermalThrottling ? 'THROTTLED' : 'PASSED'}
                  </span>
                  <span className="text-zinc-300">{metrics.maxJunctionTempCelsius} °C Peak</span>
                  <span className="text-emerald-400 font-semibold">+{105 - metrics.maxJunctionTempCelsius} °C Safety Margin</span>
                </div>

                <div className="flex justify-between items-center py-2 border-b border-white/10">
                  <div>
                    <div className="font-semibold text-white uppercase tracking-wider">Zero-DRAM Power Signoff</div>
                    <div className="text-[10px] text-zinc-500 font-mono">Compared to HBM3/DDR5 baseline system</div>
                  </div>
                  <span className="px-2 py-0.5 bg-emerald-950/50 text-emerald-400 border border-emerald-500/30 text-[9px] font-bold uppercase tracking-wider">
                    VERIFIED
                  </span>
                  <span className="text-emerald-400 font-bold">{powerMetrics.totalTdpW} Watts Total</span>
                  <span className="text-emerald-400 font-semibold">-{powerMetrics.powerSavingsPercent}% Power Reduction</span>
                </div>

                <div className="flex justify-between items-center py-2 border-b border-white/10">
                  <div>
                    <div className="font-semibold text-white uppercase tracking-wider">Static Timing Analysis (STA)</div>
                    <div className="text-[10px] text-zinc-500 font-mono">Target clock: 1.40 GHz (3nm GAAFET)</div>
                  </div>
                  <span className="px-2 py-0.5 bg-emerald-950/50 text-emerald-400 border border-emerald-500/30 text-[9px] font-bold uppercase tracking-wider">
                    CLOSED
                  </span>
                  <span className="text-zinc-300">WNS: +0.14 ns / TNS: 0.00 ns</span>
                  <span className="text-emerald-400 font-semibold">Setup & Hold Satisfied</span>
                </div>

                <div className="flex justify-between items-center py-2">
                  <div>
                    <div className="font-semibold text-white uppercase tracking-wider">Autonomous Industrial Real-Time</div>
                    <div className="text-[10px] text-zinc-500 font-mono">AEC-Q100 / IEC 61508 SIL-3 determinism</div>
                  </div>
                  <span className="px-2 py-0.5 bg-emerald-950/50 text-emerald-400 border border-emerald-500/30 text-[9px] font-bold uppercase tracking-wider">
                    CERTIFIED
                  </span>
                  <span className="text-zinc-300">Jitter: &lt;{metrics.deterministicJitterUs} µs</span>
                  <span className="text-emerald-400 font-semibold">Hard Real-Time Deadline Pass</span>
                </div>
              </div>

              {/* Silicon Summary Box */}
              <div className="p-4 bg-[#050608] border border-white/10 text-xs text-zinc-300 font-mono space-y-2 leading-relaxed uppercase tracking-wide">
                <div className="font-bold text-blue-400 text-xs uppercase tracking-wider">Design Signoff Conclusion:</div>
                <p className="text-[10px] text-zinc-400">
                  The Kimi K3 On-Silicon ASIC architecture has successfully passed full architectural signoff.
                  By integrating all pretrained weights directly into monolithic 3D {siliconConfig.memoryTech.toUpperCase()} memory tiers,
                  external DRAM bus constraints are eliminated. The dual-mode PCIe Gen 5 x16 / CXL 3.0 serial links deliver ultra-low latency prompt streaming for real-time edge robotics, automated optical inspection, and autonomous industrial control.
                </p>
              </div>

              {/* Photolithography Mask & GDSII Signoff Gate */}
              <div className="p-4 bg-[#050608] border border-white/10 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div className="space-y-1">
                  <div className="flex items-center space-x-2">
                    <Layers className="w-4 h-4 text-blue-400" />
                    <span className="text-xs font-bold text-white uppercase tracking-wider">
                      Physical Layout GDSII / OASIS Streamout & DRC
                    </span>
                  </div>
                  <p className="text-[10px] text-zinc-400 uppercase tracking-wide">
                    Execute layer stack mapping, Cu-Cu 3D direct bonding verification, and geometric DRC streamout for the {siliconConfig.dieWidthMm}x{siliconConfig.dieHeightMm}mm monolithic die.
                  </p>
                </div>
                <button
                  onClick={() => setActiveSubTab('gdsii_stream')}
                  className="flex items-center justify-center space-x-2 px-3 py-2 bg-blue-600 hover:bg-blue-500 text-white border border-blue-500 uppercase tracking-wider text-[11px] font-bold transition cursor-pointer whitespace-nowrap"
                >
                  <Play className="w-3.5 h-3.5" />
                  <span>Simulate GDSII Export</span>
                </button>
              </div>
            </div>
          )}

          {activeSubTab === 'verilog' && (
            <div className="relative">
              <pre className="p-4 bg-black border border-white/10 font-mono text-xs text-zinc-300 overflow-x-auto leading-relaxed max-h-[480px]">
                <code>{verilogCode}</code>
              </pre>
            </div>
          )}

          {activeSubTab === 'def_manifest' && (
            <div className="relative">
              <pre className="p-4 bg-black border border-white/10 font-mono text-xs text-emerald-300 overflow-x-auto leading-relaxed max-h-[480px]">
                <code>{defManifest}</code>
              </pre>
            </div>
          )}

          {activeSubTab === 'gdsii_stream' && (
            <GdsiiStreamView
              model={model}
              siliconConfig={siliconConfig}
              metrics={metrics}
              powerMetrics={powerMetrics}
            />
          )}
        </div>
      </div>
    </div>
  );
};
